---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --trailing-commas]
        exclude: uv.lock
  - repo: local
    hooks:
      - id: html-tidy
        name: HTML Tidy
        entry: .hooks/html-tidy.sh
        language: script
        types: [html]
