[tool.poetry]
name = "xhtml2epub"
version = "2.0.0"
description = "A simple EPUB authoring tool"
authors = ["Jim Wisniewski <wisnij@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
EbookLib = "^0.17.1"
lxml = "^4.3.2"

[tool.poetry.scripts]
xhtml2epub = "xhtml2epub.__main__:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
